### ISSUE TITLE
AutoIT Notepad simple test passes but doesnt launch Notepad

### ISSUE THREAD

**Issue by YouWhy** [nokia/robotframework-autoitlibrary#10]
I have this very simple robot script to launch notepad.exe and type some text. The Test passes, but it doesnt launch notepad. I am using Windows 10, python 3.7.1 and here are my versions of python packages:
```
Appium-Python-Client==0.31
decorator==4.3.0
docutils==0.14
kitchen==1.2.5
Pillow==5.4.1
pywin32==224
robotframework==3.0.4
robotframework-appiumlibrary==1.5.0.1
robotframework-autoitlibrary==1.2.2
robotframework-seleniumlibrary==3.2.0
selenium==3.141.0
six==1.11.0
urllib3==1.24.1
```

My robot scripts reads like this:
```
*** Settings ***
Library           AutoItLibrary


*** Test Cases ***
AutoIT Notepad Test
    Run    notepad.exe
    Wait For Active Window    Untitled - Notepad
    Send    This is some text
```

What am I doing wrong?

**Comment by YouWhy** [comment]
To troubleshoot, I have tried the following:
1. Removed 'Run notepad.exe' step, then manually launched notepad.exe and then this script worked.
2. I wrote a AutoIt script in Scite with all the 3 steps above and it worked.

So it appears that the 'Run' robot keyword doesnt work. Also, I am not sure why all the steps are passing!

**Comment by lucyking** [comment]
@YouWhy 
Could you help paste both success and failed robotframework running logs?  And the script you wrote in Scite.

**Comment by aswathykrishnan92** [comment]
i have the same issue. Calculator is getting started. Buut not any other application. The script in scite works fine and runs, but not the robot script. The robot results shows it as pass though even after not bringing up the application
`Run("notepad.exe")
WinWaitActive("Untitled - Notepad")
Send("Welcome to auto it!")
WinClose("Untitled - Notepad")
WinWaitActive("Notepad","Save")
Send("!n")`

This is the code is scite. For me the above troubleshoot didnt work either.
The error I am getting is Window 'UNTITLED - NOTEPAD' () failed to be active in 60 seconds
----------------------------------------------------------------

**Comment by lucyking** [comment]
@YouWhy @aswathykrishnan92 May you guys should provide the absolute fullpath of notepad.exe, such as:
```
C:\\system\\...\\notepad.exe
```
