### ISSUE TITLE
Validation problem in "Get Screen Image" and "Get Active Window Image"

### ISSUE THREAD

**Issue by mayribeirofernandes** [nokia/robotframework-autoitlibrary#13]
Hi!

I needed to comment on this validation to be able to take screenshots:

```
# if FilePath and os.path.isabs(FilePath):
#     raise RuntimeError("Given FilePath='%s' must be relative to Robot outpudir" % FilePath)
```

I work with Windows 10 and Python 3.7. Could you analyze the need for this validation?

My robot code (that works without the validation!):

```
My TestTeardown
      Get Screen Image        ${OUTPUTDIR}\\${TESTTAGS[0]}_${TESTSTATUS}.png
```

**Comment by lucyking** [comment]
Hi @mayribeirofernandes，
As the code shows, it add ${OUTPUTDIR} prefix itself: https://github.com/nokia/robotframework-autoitlibrary/blob/b39a6467972ac0edcb752de4b145da28fc9382cd/src/AutoItLibrary/__init__.py#L190

Please try to remove your comment and using:
```
My TestTeardown
      Get Screen Image        ${TESTTAGS[0]}_${TESTSTATUS}.png
```
Then after run test case you may find the *.png in the ${OUTPUTDIR}  as well.

**Comment by mayribeirofernandes** [comment]
hi @lucyking !! Thank you for answering!!! This worked for me!

I did not read the code completely, I do not have much familiarity with python yet, looking at the documentation, when I read "File Path", in my mind I was forced to pass a path and not just the file name. Maybe we can improve the documentation and change "FilePath" to "FileName" and add an example? Think about it. Thanks again!

My documentation:

Get Screen Image | FilePath | Capture a full screen image into the given FilePath. The given FilePath must be relative to Robot Framework output directory, otherwise the embedded image will not be shown in the log file.

**Comment by mayribeirofernandes** [comment]
> Hi @mayribeirofernandes，
> As the code shows, it add ${OUTPUTDIR} prefix itself:
> 
> [robotframework-autoitlibrary/src/AutoItLibrary/__init__.py](https://github.com/nokia/robotframework-autoitlibrary/blob/b39a6467972ac0edcb752de4b145da28fc9382cd/src/AutoItLibrary/__init__.py#L190)
> 
> Line 190 in [b39a646](/nokia/robotframework-autoitlibrary/commit/b39a6467972ac0edcb752de4b145da28fc9382cd)
> 
>  fullFilePath = os.path.join(self._OutputDir, FilePath) 
> Please try to remove your comment and using:
> 
> ```
> My TestTeardown
>       Get Screen Image        ${TESTTAGS[0]}_${TESTSTATUS}.png
> ```
> Then after run test case you may find the *.png in the ${OUTPUTDIR} as well.

Hi @lucyking !
I thought it worked, but it was a false positive. I deleted all the old images in my "RESULTS" folder and run it again as you instructed me, but the image was saved in the command prompt path and not in the my RESULTS folder which is my OUTPUTDIR (robot -d ./results mytestes) of the Robot Framework.

**Comment by lucyking** [comment]
Hi @mayribeirofernandes, 
This is due to RobotFramework's operating mechanism.
If you need put output in dir which outside the cmd prompt, you should use **absolute path**. 
More details please refer to: [RobotFrameworkUserGuide.html#output-directory](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#output-directory)

**Comment by mayribeirofernandes** [comment]
> Hi @mayribeirofernandes,
> This is due to RobotFramework's operating mechanism.
> If you need put output in dir which outside the cmd prompt, you should use **absolute path**.
> More details please refer to: [RobotFrameworkUserGuide.html#output-directory](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#output-directory)

Yeah! So i needed to comment on this validation again!
> 
> ```
> # if FilePath and os.path.isabs(FilePath):
> #     raise RuntimeError("Given FilePath='%s' must be relative to Robot outpudir" % FilePath)
> ```
> I work with Windows 10 and Python 3.7. Could you analyze the need for this validation?
> 
> My robot code (that works without the validation!):
> 
> ```
> My TestTeardown
>       Get Screen Image        ${OUTPUTDIR}\\${TESTTAGS[0]}_${TESTSTATUS}.png

So above works as I need it.

**Comment by lucyking** [comment]
Hi @mayribeirofernandes ,
suppose Test.robot is in C:\aaa\ , then you need put output not in C:\aaa but C:\111\ ,
you can run like this:  ```python -m robot C:\aaa\ --outputdir C:\111\```

Or, you need generate ScreenShot into diff dir for each test in one Test.robot ? If so, may need add new KeyWord to support it.

**Comment by mayribeirofernandes** [comment]
> Hi @mayribeirofernandes ,
> suppose Test.robot is in C:\aaa\ , then you need put output not in C:\aaa but C:\111\ ,
> you can run like this: `python -m robot C:\aaa\ --outputdir C:\111\`
> 
> Or, you need generate ScreenShot into diff dir for each test in one Test.robot ? If so, may need add new KeyWord to support it.

Yes, i did it!! But the image was saved in the command prompt path (C:\aaa\) and not in (C:\111\). 

In my testes i run like this: (robot **-d ./results** mytestes), 
but it did not save in **./results**, but in the execution path (**./**). So when I commented the validation and I passed the complete path (Get Screen Image        ${OUTPUTDIR}\\${TESTTAGS[0]}_${TESTSTATUS}.png), then it started to work!

**Comment by lucyking** [comment]
Hi @mayribeirofernandes,
Please use **absolute path** for output directory in cmd, such as:
robot -d  **C:\\111\\222**\results mytestes
Then in Test.robot, you needn't add ${OUTPUTDIR} prefix.

**Comment by mayribeirofernandes** [comment]
> Hi @mayribeirofernandes,
> Please use **absolute path** for output directory in cmd, such as:
> robot -d **C:\111\222**\results mytestes
> Then in Test.robot, you needn't add ${OUTPUTDIR} prefix.

Not yet!!

I tried this:
	`robot -d "C:\MeusTestes\Satelites\Central Notificações Delphi\central-notificacoes\atdd\results" testcases\suite12.robot`

and this:	
	`Get Screen Image        ${TESTTAGS[0]}_${TESTSTATUS}.png`

And, it didn't work:
	`12:27:15.008	INFO	GetScreenImage(FilePath=.\0suite12cenario01_PASS.png)`

**Comment by lucyking** [comment]
Hi @mayribeirofernandes , I‘ve try it. It seems the ScreenShot's path is not as expect then it can not show in log.html. Do you meet this issue in practice? I'll try to fix it sooner. ![pic](https://img3.doubanio.com/view/photo/l/public/p2550048632.webp)

**Comment by mayribeirofernandes** [comment]
> I‘ve try it. It seems the ScreenShot's path is not as expect then it can not show in log.html. Do you meet this issue in practice?

Yes!!! 
That's right, when I comment the validation (`if FilePath and os.path.isabs(FilePath)`) and define the full path of the image (`${OUTPUTDIR}\\${TESTTAGS[0]}_${TESTSTATUS}.png`), it **works** and appears normally in the log, because the images are saved in the same path as log.html!

![image](https://user-images.githubusercontent.com/26631940/53897510-0c845200-4015-11e9-8a0c-8d9d243dcdd1.png)

**Comment by lucyking** [comment]
yep. pls wait patiently. I'm going to fix it this weekend.

**Comment by mayribeirofernandes** [comment]
> yep. pls wait patiently. I'm going to fix it this weekend.

Great!! No hurry, I got the code and changed locally and I'm able to use it, but it's good to upload the fix for everyone! Thanks again!

**Comment by lucyking** [comment]
Hi @mayribeirofernandes,  I've fix this issuse. Just typing ```pip install robotframework-autoitlibrary -U``` to update to the newest ver and have a try. 
Thanks a lot for your kindly feedback and pls feel free to report anyother issue if you meet in future. 😄

**Comment by mayribeirofernandes** [comment]
Hi @lucyking ! It worked perfectly, thank you!

**Comment by lucyking** [comment]
> 
> 
> Hi @lucyking ! It worked perfectly, thank you!

my pleasure :cat:
