### ISSUE TITLE
Hello, the keywords of autoitlibrary library are always lost automatically. What's the reason and what's the solution?

### ISSUE THREAD

**Issue by clclclclclclcl** [nokia/robotframework-autoitlibrary#16]
![1556504018(1)](https://user-images.githubusercontent.com/49467409/56874100-0dac8b00-6a6a-11e9-9077-543392610e1f.jpg)

**Comment by lucyking** [comment]
@clclclclclclcl  Could you using ```pip install -U robotframework-autoitlibrary``` to update to newest version. Then snap both OK and NOK screenshots? Many thanks.
