### ISSUE TITLE
AutoItLibrary Install Fails when Python path contains spaces (fix included) 

### ISSUE THREAD

**Issue by wjiang100** [nokia/robotframework-autoitlibrary#20]
tried to install latest 1.2.4 on windows64/python 3.7(32bit). it gave error:
C:\sw\robotframework-autoitlibrary-master>python setup.py install
Here is from 32bit OS
%SYSTEMROOT%\system32\regsvr32.exe /S C:\Program Files (x86)\Python37-32\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    subprocess.check_call(cmd, shell=True)
  File "C:\Program Files (x86)\Python37-32\Lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '%SYSTEMROOT%\system32\regsvr32.exe /S C:\Program Files (x86)\Python37-32\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll' returned non-zero exit status 3.

then HW71 commented due to the python path contains spaces:
https://github.com/HW71/AutoItLibrary/issues/1

followed HW71's suggestion and setup is ok.
here is attached setup fix based on  1.2.4's setup.py.

[setup-fixed_v2.zip](https://github.com/nokia/robotframework-autoitlibrary/files/4098523/setup-fixed_v2.zip)

**Comment by lucyking** [comment]
hi @wjiang100, 
Many thanks for your response, I'm gonna apply the patch asap.

**Comment by lucyking** [comment]
fix by https://github.com/nokia/robotframework-autoitlibrary/commit/20b9a8537c13590dfeb126c0dc3e425f86c8fbfa
