### ISSUE TITLE
facing this issue while installing autoit...can anyone help pls?

### ISSUE THREAD

**Issue by nikhitha-tr** [nokia/robotframework-autoitlibrary#24]
pip install robotframework-autoitlibrary
Collecting robotframework-autoitlibrary
  Using cached robotframework-autoitlibrary-1.2.5.tar.gz (696 kB)
Requirement already satisfied: pywin32 in c:\python\python 3.8\lib\site-packages (from robotframework-autoitlibrary) (228)
Requirement already satisfied: pillow in c:\python\python 3.8\lib\site-packages (from robotframework-autoitlibrary) (7.2.0)
Using legacy 'setup.py install' for robotframework-autoitlibrary, since package 'wheel' is not installed.
Installing collected packages: robotframework-autoitlibrary
    Running setup.py install for robotframework-autoitlibrary ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python 3.8\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\niktr\\AppData\\Local\\Temp\\pip-install-o_n58w0p\\robotframework-autoitlibrary\\setup.py'"'"'; __file__='"'"'C:\\Users\\niktr\\AppData\\Local\\Temp\\pip-install-o_n58w0p\\robotframework-autoitlibrary\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\niktr\AppData\Local\Temp\pip-record-i6ef1_0f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python 3.8\Include\robotframework-autoitlibrary'
         cwd: C:\Users\niktr\AppData\Local\Temp\pip-install-o_n58w0p\robotframework-autoitlibrary\
    Complete output (10 lines):
    Don't think we need to unregister the old one...
    Here is from 32bit OS
    %SYSTEMROOT%\system32\regsvr32.exe /S c:\python\python 3.8\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\niktr\AppData\Local\Temp\pip-install-o_n58w0p\robotframework-autoitlibrary\setup.py", line 75, in <module>
        subprocess.check_call(cmd, shell=True)
      File "c:\python\python 3.8\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '%SYSTEMROOT%\system32\regsvr32.exe /S c:\python\python 3.8\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll' returned non-zero exit status 3.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python 3.8\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\niktr\\AppData\\Local\\Temp\\pip-install-o_n58w0p\\robotframework-autoitlibrary\\setup.py'"'"'; __file__='"'"'C:\\Users\\niktr\\AppData\\Local\\Temp\\pip-install-o_n58w0p\\robotframework-autoitlibrary\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\niktr\AppData\Local\Temp\pip-record-i6ef1_0f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python 3.8\Include\robotframework-autoitlibrary' Check the logs for full command output.

**Comment by lucyking** [comment]
Hi @nikhitha-tr, may you have a try:  
>Click on “Start”, type “cmd”, right-click > “Run as Administrator“.

**Comment by vinayvennela** [comment]
@nikhitha-tr 
I faced the same issue earlier, and it was due to spaces in the python path
In your case "File "c:\python\python 3.8\lib\subprocess.py"  notice the space between "python" and "3.8"

Change the python install directory and that should resolve the issue.

**Comment by nikhitha-tr** [comment]
> Hi @nikhitha-tr, may you have a try:
> 
> > Click on “Start”, type “cmd”, right-click > “Run as Administrator“.

**Comment by nikhitha-tr** [comment]
i tried to run as administrator but still the same issue

**Comment by lucyking** [comment]
Hi @nikhitha-tr , please run `pip install -U robotframework-interfacelibrary` to install the newest release version, which fixed this issue already.
