### ISSUE TITLE
Return ProcessID when application is launched with the keyword Run

### ISSUE THREAD

**Issue by vinayvennela** [nokia/robotframework-autoitlibrary#25]
As per standard AutoIt implementation, run() returns the PID of the application that was launched which can be used further.

However the keyword "Run" doesn't return anything, we should add this implementation so that the output PID can be used later in keywords like "Process Close" etc.

This is a feature request, and I'm happy to create a PR for the same

**Comment by vinayvennela** [comment]
Created PR too. 
Please have a look

**Comment by lucyking** [comment]
it looks good. many thanks ; )

**Comment by lucyking** [comment]
@vinayvennela could you kindly move Line291-294 to the left one char space to keep align?

**Comment by vinayvennela** [comment]
@lucyking Thanks for pointing that out. Updated the PR now

**Comment by vinayvennela** [comment]
@lucyking What is the date for the next version release?
Would love to contribute if help is required in other PRs too.

**Comment by lucyking** [comment]
@vinayvennela v1.2.6 released. I'll gonna fix #24 soon, it's not difficult. Thanks a lot for your comment info on that issue.

**Comment by vinayvennela** [comment]
v1.2.6 released.
