### ISSUE TITLE
error while install robotframework-autoitlibrary

### ISSUE THREAD

**Issue by kumarkrish85** [nokia/robotframework-autoitlibrary#30]
I face the below error while installing autoitlibrary using pip

Collecting robotframework-autoitlibrary
  Using cached robotframework-autoitlibrary-1.2.7.tar.gz (696 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools,
 tokenize; sys.argv[0] = '"'"'C:\\Users\\J84500159SA\\AppData\\Local\\Temp\\pip-
install-t6qfhbnb\\robotframework-autoitlibrary_2208d6c3255040a9b373c8a6a4a46df1\
\setup.py'"'"'; __file__='"'"'C:\\Users\\J84500159SA\\AppData\\Local\\Temp\\pip-
install-t6qfhbnb\\robotframework-autoitlibrary_2208d6c3255040a9b373c8a6a4a46df1\
\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read()
.replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"
'"'exec'"'"'))' egg_info --egg-base 'C:\Users\J84500159SA\AppData\Local\Temp\pip
-pip-egg-info-lmzdro17'
         cwd: C:\Users\J84500159SA\AppData\Local\Temp\pip-install-t6qfhbnb\robot
framework-autoitlibrary_2208d6c3255040a9b373c8a6a4a46df1\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\J84500159SA\AppData\Local\Temp\pip-install-t6qfhbnb\robotfr
amework-autoitlibrary_2208d6c3255040a9b373c8a6a4a46df1\setup.py", line 93, in <m
odule>
        destPath = os.path.normpath(os.path.join(os.getenv("HOMEDRIVE"), r"\Robo
tFramework\Extensions\AutoItLibrary"))
      File "c:\program files\python38\lib\ntpath.py", line 78, in join
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1f/e7/944c114dbb2db2
3d93e47c3449df92aaa823e57b94d861f963597ebea3b4/robotframework-autoitlibrary-1.2.
7.tar.gz#sha256=4b154340b95a5f848c00af3f079ae41587270741925f430d61ffc5c1db00ad40
 (from https://pypi.org/simple/robotframework-autoitlibrary/). Command errored o
ut with exit status 1: python setup.py egg_info Check the logs for full command

i am using 64 bit windows 7 OS and python installed on C:\programfiles\python38 folder, there is no space. tried in administrator cmd mode

please advice

**Comment by lucyking** [comment]
It seems that ```os.getenv("HOMEDRIVE")``` reutrns NoneType. 
May in Windows 7 the HOMEDRIVER is not defined yet. To workaround, please replace this line  https://github.com/nokia/robotframework-autoitlibrary/blob/20b9a8537c13590dfeb126c0dc3e425f86c8fbfa/setup.py#L93
with ```destPath = os.path.normpath(os.path.join("C:", r"\RobotFramework\Extensions\AutoItLibrary")) ```

And I will try deliver a offical version to fix this issue in future.

**Comment by kumarkrish85** [comment]
Thanks for the help. I have already resolved the issue by setting the HOMEDRIVE through path variable.

**Comment by lucyking** [comment]
it's fine.
