### ISSUE TITLE
strange H: disk required

### ISSUE THREAD

**Issue by liuy365** [nokia/robotframework-autoitlibrary#32]
Both directly install or download the gz package to local disk complain same error: creating H:\ disk
And both Python 2.7, python 3.9 tried.

<pre>
c:\>pip install robotframework-autoitlibrary --proxy http://10.144.1.10:8080
Collecting robotframework-autoitlibrary
  Using cached robotframework-autoitlibrary-1.2.7.tar.gz (696 kB)
Collecting pywin32
  Downloading pywin32-301-cp39-cp39-win_amd64.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 726 kB/s
Collecting pillow
  Downloading Pillow-8.3.1-1-cp39-cp39-win_amd64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 726 kB/s
Using legacy 'setup.py install' for robotframework-autoitlibrary, since package 'wheel' is not installed.
Installing collected packages: pywin32, pillow, robotframework-autoitlibrary
    Running setup.py install for robotframework-autoitlibrary ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-s1_eqmbv\\robotframework-autoitlibrary_f394e44522e847bb9826b988ff16e5ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-s1_eqmbv\\robotframework-autoitlibrary_f394e44522e847bb9826b988ff16e5ab\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx\AppData\Local\Temp\pip-record-f1jdshr9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\xxx\appdata\local\programs\python\python39\Include\robotframework-autoitlibrary'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-s1_eqmbv\robotframework-autoitlibrary_f394e44522e847bb9826b988ff16e5ab\
    Complete output (25 lines):
    %SYSTEMROOT%\system32\regsvr32.exe /S "c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll"
    python "c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\win32com\client\makepy.py" "c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll"
    Generating to C:\Users\xxx\AppData\Local\Temp\gen_py\3.9\F8937E53-D444-4E71-9275-35B64210CC3Bx0x1x0.py
    Building definitions from type library...
    Generating...
    Importing module
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\AutoItLibrary
    copying src\AutoItLibrary\Counter.py -> build\lib\AutoItLibrary
    copying src\AutoItLibrary\Logger.py -> build\lib\AutoItLibrary
    copying src\AutoItLibrary\__init__.py -> build\lib\AutoItLibrary
    running install_lib
    copying build\lib\AutoItLibrary\Counter.py -> c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary
    copying build\lib\AutoItLibrary\Logger.py -> c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary
    copying build\lib\AutoItLibrary\__init__.py -> c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary
    byte-compiling c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary\Counter.py to Counter.cpython-39.pyc
    byte-compiling c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary\Logger.py to Logger.cpython-39.pyc
    byte-compiling c:\users\xxx\appdata\local\programs\python\python39\Lib\site-packages\AutoItLibrary\__init__.py to __init__.cpython-39.pyc
    running install_data
    creating H:\
    error: could not create 'H:\': The system cannot find the path specified
----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\xxx\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-s1_eqmbv\\robotframework-autoitlibrary_f394e44522e847bb9826b988ff16e5ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-s1_eqmbv\\robotframework-autoitlibrary_f394e44522e847bb9826b988ff16e5ab\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx\AppData\Local\Temp\pip-record-f1jdshr9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\xxx\appdata\local\programs\python\python39\Include\robotframework-autoitlibrary' Check the logs for full command output.
</pre>

**Comment by lucyking** [comment]
pls run this cmd manually. If the HOMEDRIVE ==  __H:__, you should set it properly in Windows OS .
> [setup.py#L93](https://github.com/nokia/robotframework-autoitlibrary/blob/master/setup.py#L93)
```
import os
destPath = os.path.normpath(os.path.join(os.getenv("HOMEDRIVE"), r"\RobotFramework\Extensions\AutoItLibrary"))
print(destPath)

```

**Comment by lucyking** [comment]
issue fixed after setting the HOMEDRIVE well.
