### ISSUE TITLE
Unable to install - win32com issue?

### ISSUE THREAD

**Issue by Mavnus04** [nokia/robotframework-autoitlibrary#34]
Getting the following error after running the install command on an admin prompt
```

C:\Windows\system32>pip install robotframework-autoitlibrary --no-cache-dir
Collecting robotframework-autoitlibrary
  Downloading robotframework-autoitlibrary-1.2.7.tar.gz (696 kB)
     |████████████████████████████████| 696 kB 1.3 MB/s
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pywin32 in c:\users\username\appdata\roaming\python\python37\site-packages (from robotframework-autoitlibrary) (301)
Requirement already satisfied: pillow in c:\program files\python37\lib\site-packages (from robotframework-autoitlibrary) (8.3.2)
Using legacy 'setup.py install' for robotframework-autoitlibrary, since package 'wheel' is not installed.
Installing collected packages: robotframework-autoitlibrary
    Running setup.py install for robotframework-autoitlibrary ... error
    ERROR: Command errored out with exit status 2:
     command: 'C:\Program Files\Python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USE~1.AME\\AppData\\Local\\Temp\\pip-install-0w7o5y10\\robotframework-autoitlibrary_fa8e6ee5cad94f138d73f7813ef4bfdd\\setup.py'"'"'; __file__='"'"'C:\\Users\\USE~1.AME\\AppData\\Local\\Temp\\pip-install-0w7o5y10\\robotframework-autoitlibrary_fa8e6ee5cad94f138d73f7813ef4bfdd\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USE~1.AME\AppData\Local\Temp\pip-record-0kc7z3h1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python37\Include\robotframework-autoitlibrary'
         cwd: C:\Users\USE~1.AME\AppData\Local\Temp\pip-install-0w7o5y10\robotframework-autoitlibrary_fa8e6ee5cad94f138d73f7813ef4bfdd\
    Complete output (3 lines):
    Don't think we need to unregister the old one...
    %SYSTEMROOT%\system32\regsvr32.exe /S "C:\Program Files\Python37\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll"
    AutoItLibrary requires win32com. See http://starship.python.net/crew/mhammond/win32/.
    ----------------------------------------
ERROR: Command errored out with exit status 2: 'C:\Program Files\Python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USE~1.AME\\AppData\\Local\\Temp\\pip-install-0w7o5y10\\robotframework-autoitlibrary_fa8e6ee5cad94f138d73f7813ef4bfdd\\setup.py'"'"'; __file__='"'"'C:\\Users\\USE~1.AME\\AppData\\Local\\Temp\\pip-install-0w7o5y10\\robotframework-autoitlibrary_fa8e6ee5cad94f138d73f7813ef4bfdd\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USE~1.AME\AppData\Local\Temp\pip-record-0kc7z3h1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python37\Include\robotframework-autoitlibrary' Check the logs for full command output.
```

My environment:
Windows 10 Enterprise
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32

Looks like win32com might be related to the issue? But I have pywin32 installed.

**Comment by lucyking** [comment]
why you can install Python 3.7.9 [MSC v.1900 __64 bit__ (AMD64)] on __win32__?

**Comment by Mavnus04** [comment]
Not sure I understand your question.  
I ran the 'Windows x86-64 executable installer' to install python 3.7.9 from the python site, https://www.python.org/downloads/release/python-379/
My windows 10 is 64bit. 

    C:\>python 
    Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32

    C:\>python --version
    Python 3.7.9

Is there something else I can try to install the robotframework-autoitlibrary? 

I've developed a couple of GUIs with AutoIT before. 
I have AutoIT v3 currently installed. 
![image](https://user-images.githubusercontent.com/24551506/149380747-a1207b92-2e9c-4a16-b79c-4f180c674187.png)

**Comment by lucyking** [comment]
Oooo, I wonder it should be "__win64__". However, I found o my 64 bit win10, python does show win32 indeed. My bad.

for your issue, it failed in these lines during install:
[setup.py#L76](https://github.com/nokia/robotframework-autoitlibrary/blob/master/setup.py#L76)
```
            makepy = os.path.normpath(os.path.join(get_python_lib(), "win32com/client/makepy.py"))
            #
            # Make sure we have win32com installed
            #
            if not os.path.isfile(makepy) :
                print("AutoItLibrary requires win32com. See http://starship.python.net/crew/mhammond/win32/.")
                sys.exit(2)
```
and there's two python lib dir on your PC:
```
Requirement already satisfied: pywin32 in c:\users\username\appdata\roaming\python\python37\site-packages (from robotframework-autoitlibrary) (301)
Requirement already satisfied: pillow in c:\program files\python37\lib\site-packages (from robotframework-autoitlibrary) (8.3.2)
```

You need to install win32com in the get_python_lib() path.

**Comment by Mavnus04** [comment]
I was able to uninstall pywin32 from the username\appdata\roaming\python\python37\site-packages and re-install into the program files\python37\lib\site-packages. 
Then the robotframework-autoitlibrary successfully installed. 

For the future, would it be possible for robotframework-autoitlibrary to check/use multiple locations for site-packages?  I honestly didn't know I had packages stored in these two locations.  I actually have quite a few packages in both locations and have never run into this issue before with installing other packages. I am going to look into the pros/cons of the packages being installed in multiple locations. 

Did a little quick searching and it looks like distutils is deprecated in 3.10, and being removed in 3.12. If you want to stay compatible with future versions of python, you may want to check out other options. Not telling you what to do, just making a suggestion. 
https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated

Thanks again for your help.

**Comment by lucyking** [comment]
Hi @Mavnus04, yes it needs add support to search both directories indeed.
At present we can use
```
import os
print os.getenv('APPDATA')
```
to get `username\appdata\roaming\` path prefix. But can not sure if all the python version will in  such `*\roaming\python\python[[:digit:]]{2}\site-packages` format. You re-install solution is one temporarily workaround. 
We will support multi site-packages paths soon. Many thanks for your issue &&  suggestion.

**Comment by lucyking** [comment]
v1.2.8 fix this issue already.
