### ISSUE TITLE
Handling File Upload using AutoIT Library not working as expected 

### ISSUE THREAD

**Issue by vishnuprakash9845** [nokia/robotframework-autoitlibrary#35]
### I am trying to Automate the File upload using AUTOIT, but when handled the File upload popup is coming up twice.

**Below are the steps followed after browser launch**

Step-1: Click on Choose File button
Step-2: Waited for Active Window
Step-3: Control send path of file
Step-4: control click on open button and popup closed , but again its opening (Attached the code and gif of recording)

## **Code**
`
*** Settings ***
Documentation  We are testing 'File upload usinf AutoIT' for the website 'https://cgi-lib.berkeley.edu/ex/fup.html'
Library    SeleniumLibrary
Library    AutoItLibrary
*** Variables ***
${inputElement}    css:input[name='upfile']

*** Test Cases ***
My Fileupload2
    open browser        https://cgi-lib.berkeley.edu/ex/fup.html      chrome
    Maximize Browser Window
    Double Click Element    ${inputElement}
    Wait For Active Window    Open    ${SPACE} 
    sleep    1s
    control send  [CLASS:#32770; TITLE:Open]  ${EMPTY}  [CLASSNN:Edit1]  C:\\Auto\\index.html
    sleep    3s
    control click  [CLASS:#32770; TITLE:Open]  ${EMPTY}  [CLASSNN:Button1]
    sleep    1s
    #Click Element    xpath://input[@type='submit']
    sleep    1s
    Close Browser
`

**Recording**

![AutoITPopup](https://github.com/nokia/robotframework-autoitlibrary/assets/24207575/ae15eabc-d4ed-4002-be24-353751436c10)

**Below are the Technical details of the versions used**

Windows 10 Enterprise OS
Python 3.11.1

I installed all the dependencies from the requirements file. 

![image](https://github.com/nokia/robotframework-autoitlibrary/assets/24207575/bd7c83c3-2647-4780-a00f-d79c3138e8d7)

**I request anyone has expertise or insights to share, I would greatly appreciate your support and contributions in addressing this issue.**

@lucyking @qitaos @mihaiparvu @mihaiparvu @josoinin 

Thank you all in advance for being a part of our supportive community!

**Comment by lucyking** [comment]
Hi @vishnuprakash9845 , if `index.html` uploaded properly, the web will show its filename. So I think the `Open` button is not clicked as expect.
![image](https://github.com/nokia/robotframework-autoitlibrary/assets/4670642/e864edc4-94a4-44eb-aba8-7aeff8665c65)

**Comment by vishnuprakash9845** [comment]
> Hi @vishnuprakash9845 , if `index.html` uploaded properly, the web will show its filename. So I think the `Open` button is not clicked as expect. ![image](https://user-images.githubusercontent.com/4670642/257711845-e864edc4-94a4-44eb-aba8-7aeff8665c65.png)

Ok, Thanks for the response. 

But I am clicking on it using control click [CLASS:#32770; TITLE:Open] ${EMPTY} [CLASSNN:Button1].

Let me try clicking by another method.

**Comment by lucyking** [comment]
Hi @vishnuprakash9845, if no further problem I will close this issue.
