### ISSUE TITLE
issue install autoitlibrary

### ISSUE THREAD

**Issue by lng60044** [nokia/robotframework-autoitlibrary#36]
can anyone help me with the issue below 

![autoitlibrary installation issue](https://github.com/nokia/robotframework-autoitlibrary/assets/86804618/7866d15d-8ee9-40da-8f38-4c7479a8c08d)

**Comment by lucyking** [comment]
Hi @lng60044, it's just warning print which will not affect usage.

**Comment by lucyking** [comment]
close as no further discuss.
