### ISSUE TITLE
Import AutoITLibrary error

### ISSUE THREAD

**Issue by dileepreddy9** [nokia/robotframework-autoitlibrary#37]
Hi All, I have installed AutoIT Library through EXE file. also installed through pip command after opening commandprompt as administrator. however when I keep the library in my resource file in robot framework and run, getting the below error.

resources.robot' on line 16: Importing library 'AutoITLibrary' failed: ModuleNotFoundError: No module named 'AutoITLibrary'
Traceback (most recent call last):
  None please help

**Comment by lucyking** [comment]
@dileepreddy9  please try to use `AutoItLibrary` in resources.robot

**Comment by lucyking** [comment]
close with no response for long time.

**Comment by dileepreddy9** [comment]
Hi Lucking, Thank you for your response. my issue got resolved. I was entering IT instead of ItLibrary.

Thanks a lot for your response.

Cheers,
Dileep
