### ISSUE TITLE
Auto It Library Send keywords are not working on Latest chrome version 68.0

### ISSUE THREAD

**Issue by SivaArunBalaji** [nokia/robotframework-autoitlibrary#4]
Hi,

The send keywords(Send,ControlSend) are not working to handle window authentication pop up in the latest chrome version 68.0 even though I have tried with the latest chrome driver version 41. Kindly advise.
Note: I have used these keywords and it was working fine in Chrome version 64.0 & Driver version 32

**Comment by lucyking** [comment]
@SivaArunBalaji 
This lib is just a wrapper of AutoIt, which is not the newest version. 
May there's some thing update of [AutoIt](http://www.autoitscript.com/autoit3/index.shtml) to fix this issue.
Suggest you use newest AutoIt directly to find the reason. Any info of your progress is appreciate.
