### ISSUE TITLE
Send keyword is not working on IE 11

### ISSUE THREAD

**Issue by xenogew** [nokia/robotframework-autoitlibrary#7]
FYI

- Python 3.7
- robotframework 3.0.4
- selenium 3.14.0
- robotframework-seleniumlibrary 3.1.1
- IEDriverServer 3.14.0.0 (32 bit)
- robotframework-autoitlibrary 1.2.2 then after install with `pip install robotframework-autoitlibrary` I got all dependencies
- Pillow 5.3.0
- pywin32 244 (64bit)

OS: Windows 10 (v 1809)

What I've tried is call `Send` keyword to `{ENTER}` for the Windows Security window, but there's nothing happen to the Windows Security dialog as I expected.

What's the things I missed?

**Comment by lucyking** [comment]
Please verify it manually first. 
Can you locate Windows Security window by AutoIt?
